CC=g++
BIN=bin/
all: s1 s2 s3 s4 s5 s6 s7

s1:
	$(CC) -o $(BIN)s1 s1.cpp

s2:
	$(CC) -o $(BIN)s2 s2.cpp

s3:
	$(CC) -o $(BIN)s3 s3.cpp

s4:
	$(CC) -o $(BIN)s4 s4.cpp

s5:
	$(CC) -o $(BIN)s5 s5.cpp

s6:
	$(CC) -o $(BIN)s6 s6.cpp

s7:
	$(CC) -o $(BIN)s7 s7.cpp

clean:
	-rm -rf $(BIN)*
